### PR TITLE
Feature/gsd 1260 implement kyc 2

### PR DESCRIPTION
**Pull request by joaomsa**
Also ended up doing a slight rewrite to use the REST v3 api since I couldn't really find the documentation of the CORE v3 api, and to have a more direct type mapping of the api's resposes.

### CODE REVIEW

**Comment by jdconley** [comment]
I'm not completely familiar with how the JSON lib will handle enums. Make sure that if we receive an unknown enum value from SynapsePay that we don't get an exception. Typically API publishers consider adding an enum value to be a change that doesn't require strict versioning. Have been bit by this before.

**Comment by jdconley** [comment]
There are many usages of the "JsonProperty" attribute, when it looks like that translation from .NET-style casing to lcase_with_underscores could be handled for all objects with a global type converter or some such in the JSON lib. We actually do something similar in RealCrowd's serialization stack. But, if it isn't a quick project, don't worry about it.

**Comment by joaomsa** [comment]
The JsonPropertyAttribute does override the value generated by the contracts resolver when present as expected from my tests.

Not sure which version you've encountered that bug but I'm using the same 7.0.1 version as our main repo, not the latest 9.x version.

**Comment by jdconley** [comment]
@joaomsa That bug on the contract resolver was a few years ago. Guess it got worked out.

**Comment by jdconley** [comment]
@joaomsa you still have this assigned to yourself. Looks like you're done with the comment I had, though. :shipit:

**Comment by jdconley** [comment]
Maybe we should gzip the binary serialized payloads? https://msdn.microsoft.com/en-us/library/system.io.compression.gzipstream%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396

**Pull request merged**
